### ISSUE TITLE
Medienordner-Rechte werden nicht berücksichtigt

### ISSUE THREAD

**Issue by cukabeka** [nightstomp/rex_multiupload#10]
Bei einem Benutzer, der nur auf bestimmte Kategorien Zugriff hat, werden beim Kategorie-Dropdown alle Kategorien angezeigt.

**Comment by hirbod** [comment]
Hast du auch mal geprüft, ob auch tatsächlich in diese Kategorie synchronisiert wird?

**Comment by hirbod** [comment]
Kein Feedback - closed!
