### ISSUE TITLE
Widget Unterstützung

### ISSUE THREAD

**Issue by tbaddade** [nightstomp/rex_multiupload#11]
Wird der Medienpool von einem Widget aufgerufen, wäre es fein wenn der Button "Hinzufügen und übernehmen" erscheint.

**Comment by hirbod** [comment]
Im Uploader? Oder generell? Weil generell sollte das funktionieren... ich übergebe den rex_input_opener

**Comment by tbaddade** [comment]
Im Uploader selbst. Da waren keine Buttons wie bei "Medium hinzufügen" wenn ich von einem Widget komme.

**Comment by hirbod** [comment]
Ok, finde das Feature auch wichtig. Vorschlag: nach dem Upload in der Uploadliste jeweils auf der Datei ein "Hinzufügen" und man könnte auch überlegen in der Liste Checkboxen einzubauen, um mehrere Dateien gleichzeitig hinzuzufügen.

**Comment by tbaddade** [comment]
Checkboxen sind nur sinnvoll, wenn du auch eine "selektiere alle" Checkbox anbietest und dann alle auf einmal in die MediaList wirfst. Ansonsten ist der Klick über Checkbox unnötig, da man gleich auf den Button "übernehmen" klicken kann.

**Comment by hirbod** [comment]
Ja, die Checkboxfunktion baue ich im neuen Uploader erst ein.
Die Funktion ist jetzt in Version 3.1.0 umgesetzt. Viel Spaß & danke!
