### ISSUE TITLE
Dateien aktualisieren

### ISSUE THREAD

**Issue by tbaddade** [nightstomp/rex_multiupload#12]
vielleicht via Checkbox "Dateien aktualisieren" bevor die Dateien in die Dropzone landen?

**Comment by hirbod** [comment]
Ich verstehe das Ticket leider nicht?

**Comment by tbaddade** [comment]
Aktuell kann ich Dateien nur zum Medienpool hinzufügen. Würde gern den Uploader auch für das aktualisieren von Dateien verwenden, wenn der Dateiname bereits vorhanden ist.

**Comment by hirbod** [comment]
Hi, ok, jetzt hab ichs. Das sollte eigentlich gar nicht so schwer sein. Ich darf dann nur nicht die Filename-Geschichte vorher aufrufen, damit das Überschreiben funktionieren kann.

Also es ist dann nichts anderes wie ein FTP-Overwrite. Sehe ich das richtig?
