### ISSUE TITLE
Infolink verweist auf falsches Repos [3.1.0]

### ISSUE THREAD

**Issue by dergel** [nightstomp/rex_multiupload#14]
https://github.com/nightstomp/rexdaxo_multiupload

->

https://github.com/nightstomp/rex_multiupload

**Comment by hirbod** [comment]
Wo hab ich den Link fehlerhaft eingetragen? Würde es gern anpassen.

**Comment by dergel** [comment]
/redaxo/index.php?page=rex_multiupload&subpage=info

**Comment by hirbod** [comment]
fixed
