### ISSUE TITLE
compat class abhaenigkeit

### ISSUE THREAD

**Issue by dergel** [nightstomp/rex_multiupload#15]
Ab Version 4.7 wird die compat Klasse wahrscheinlich nicht mehr eingebunden.. deswegen schonmal als Info.

Fatal error: Call to undefined function rex_mediapool_addMediacatOptionsWPerm() in /Users/jankristinus/Desktop/workspace/redaxo4/redaxo/include/addons/rex_multiupload/classes/upload.class.php on line 217

lg

**Comment by hirbod** [comment]
ok, werd ich beobachten, ob die nun wirklich rausfliegt :p
