### ISSUE TITLE
Paste from Clipboard

### ISSUE THREAD

**Issue by cukabeka** [nightstomp/rex_multiupload#17]
Idee: Ist zwar nicht Multi, aber wäre praktisch:
http://www.fabiobiondi.com/blog/2012/10/export-and-save-a-screenshot-of-an-html5-canvas-using-php-jquery-and-easeljs/

**Comment by hirbod** [comment]
Seh ich jetzt erstmal nicht für das AddOn. Aber danke für die Anregung.
