### ISSUE TITLE
Dropzone :)

### ISSUE THREAD

**Issue by ghost** [nightstomp/rex_multiupload#2]
Hi!

Ich bin kürzlich über diesen Service hier gestossen: http://kraken.io/

Hier finde ich es ganz cool, dass Upload Button und die "Dropzone" extra sind. So sieht man gleich viel besser, was man für Auswahlmöglichkeiten hat um Files hochzuladen. 

Desweiteren finde ich den Style der Dropzone (gestrichelte Linie, nettes Icon in der mitte) ganz cool. Sieht aufjedenfall nicer aus finde ich, wie der rote Button im Multiuploader. Btw: rot ist auch nicht so optimal gewählt, da diese Farbe eigentlich eher für Fehlermeldungen etc. steht. Grün wäre dann eigentlich besser :)

Nur mal so als Anregung/Idee...

**Comment by hirbod** [comment]
Ich finde einen Button nach wie vor besser, ist aber eine Ansichtssache. Deshalb werde ich das erstmal nicht ändern. Die Hinweise mit der Farbe sind richtig, war mir selbst schon ein Dorn im Auge. Ich habe die komplette Optik mal etwas angepasst und auch einheitlicher gestaltet. Default Blau, Grün bei Hover/Erfolg, Rot bei Fehler oder wenn man den Button nicht richtig droped.
