### ISSUE TITLE
Multiuploader übernimmt nicht die Katagorieeinstellung aus dem Medienpool

### ISSUE THREAD

**Issue by ghost** [nightstomp/rex_multiupload#3]
Wenn ich eine Kategeorie im Mediepool wechsle, dann wird diese von REDAXO automatisch als Default gesetzt und egal auf welche Medienpool-Page ich springe ist diese vorausgewählt. 

Wenn ich allerdings zum Multiuploader springe, ist grundsätzlich keine Kategorie ausgewählt. Hier wäre es also vielleicht ganz nett die aktuelle Kategorieeinstellung von REDAXO zu übernehmen.

Und wenn ich dann die Kategorie im Multiuploader wechsle, wäre es vielleicht auch ganz cool wenn der Multiploader sich diese wieder merkt bzw. als Default für den ganzen Medienpool setzt.

**Comment by hirbod** [comment]
Guter Hinweis, wurde ich bereits mehrfach gefragt. Habs implementiert. Jedoch greift die Einstellung vom Multiuploader erst, wenn eine Datei ausgewählt wurde (wg. Ajax, wollte nicht extra bei der Auswahl noch nen Request abschicken). Evtl mache ich das demnächst noch etwas schicker über JS-Cookies, mal sehen. Es funktioniert jedoch schon mal.

Die Auswahl wird jetzt auch bei jedem reload auf den zuletzt bekannten Stand gesetzt
