### ISSUE TITLE
Hinweis auf neuen EP PAGE_MEDIAPOOL_OUTPUT

### ISSUE THREAD

**Issue by ghost** [nightstomp/rex_multiupload#4]
Damit sollte der Multiuploader in Zukunft auch ohne Patches auskommen :)
https://github.com/redaxo/redaxo4/commit/e1f594d73291acc30472b301ca1bee94a2655e99

Falls du den neuen EP mal testen kannst vor Release von 4.5 wäre das vielleicht nicht schlecht

Hier noch das Equivalent für die Artikelansicht.
https://github.com/redaxo/redaxo4/issues/94#issuecomment-13180197

**Comment by hirbod** [comment]
Thx für den Hinweis, hab ich implementiert
