### ISSUE TITLE
Multiupload / Medienpool

### ISSUE THREAD

**Issue by olien** [nightstomp/rex_multiupload#6]
Hi Hirbod,

nach der Installation und Aktivierung des Addons wird der Medienpool nicht mehr angezeigt.

Fehler:

Fatal error: rexCallFunc: Function "rex_multiupload_menu_insert" not found! in /Applications/MAMP/htdocs/rex45b/redaxo/include/functions/function_rex_extension.inc.php on line 157

REDAXO: 4.5b6.0
PHP: 5.4.4

LG
Oliver

**Comment by ghost** [comment]
kann @olien s meldung bestätigen. tritt bei mir auch auf.

REDAXO: 4.5.0 (eine der neusten Versionen aus GitHub)
PHP: 5.4.7

**Comment by hirbod** [comment]
Wie kann das sein? :S - Bin total verwirrt... Hier und auf der CeBIT hat das sauber funktioniert...

**Comment by ghost** [comment]
hmmm, ich verstehe es auch noch nicht. habe gerade mal oberflächlich draufgeschaut. hier mal paar fragen um das prob vielleicht eingrenzen zu können: php version? existiert funktion rex_multiupload_menu_insert wirklich? neuste rex beta genommen? mal so probiert (nur halt umschreiben für die mp ep's): https://github.com/redaxo/redaxo4/issues/94#issuecomment-13180197

**Comment by gharlan** [comment]
Ich hab das Addon gerade mal geladen und kann den Fehler in der aktuellen 4.5 nicht nachvollziehen. Wenn man Redaxo von github verwendet, muss man nur dran denken, die class.compat.php einzukommentieren. Aber wenn man das vergisst, kommt eine andere Meldung als die oben.

PS: @Hirbod Hab nur kurz drüber geschaut, aber sieht schick aus :)

**Comment by gharlan** [comment]
@RexDude Kannst du mal schauen, was `$include_files` bei dir an [dieser Stelle](https://github.com/nightstomp/redaxo_multiupload/blob/master/config.inc.php#L81) enthält?

**Comment by ghost** [comment]
witzig, wollt mir das auch grad mal genauer anschauen :) ...feedback kommt...

**Comment by ghost** [comment]
ok, habs schon gefunden. bei mir hieß das addon verzeichnis "redaxo_multiupload". es muss aber "rex_multiupload" heissen. dummerweise kam hier auch nicht die fehlermeldung, die eigentlich kommen sollte :/ @gharlan ???

@Hirbod sehr nice das ganze. insbesondere die neue blaue dropzone mit den abgerundeten ecken macht echt was her :) nur der grüne hover effekt passt irgendwie nicht finde ich, da grün eigentlich gar nicht aftaucht im agk_skin (ausser bei rex_info's) --> ein hell blau und ein dunkel blau aus dem agk_skin nehmen? ...oder halt so belassen :). aber sonst super geil!!! thx!

vielleicht ist damit auch ralfs prob ausm forum beseitigt?

**Comment by gharlan** [comment]
@Hirbod Bitte [hier](https://github.com/nightstomp/redaxo_multiupload/blob/master/install.inc.php#L5) den Addonnamen fest setzen, und ihn nicht aus den Parametern holen. Denn dann liefert Redaxo eine Fehlermeldung, wenn der Addonordner falsch benannt ist, aber so kann Redaxo das nicht erkennen.

**Comment by hirbod** [comment]
Hab in der README extra betont, dass das Verzeichnis umbenannt werden muss. Mich nervt das mit den Ordnernamen. Ich werde das in Zukunft wohl so machen, das ich hier in GIthub die Hierarchie verändere und "redaxo_multiupload -> rex_multiupload" ablege. Dann sollte hoffentlich allen klar sein, das sie nur das innere Verzeichnis hochladen dürfen.

@gharlan Wollte bewusst darauf verzichten den String fest anzugeben. Kann ich aber ändern, wenn das hilft.

Oder ich werde schauen, ob ich irgendwo fest "rex_multiupload" eingebaut habe und ebenfalls durch den $mypage String ersetzen, dann sollte das AddOn funktionieren, egal wie das Verzeichnis lautet. Entspricht aber nicht der Update-AddOnKey norm... alles nervig! :D

**Comment by gharlan** [comment]
Ich würde mich schon auf einen Key festlegen, und den dann fest verwenden und Redaxo die Fehlermeldung ausgeben lassen, wenn der Ordner falsch heißt. So ist es jedenfalls gedacht.
redaxo/redaxo4#78

**Comment by ghost** [comment]
@Hirbod auf jedenfall den key verwenden, so wie das andere addons auch machen. du wirst dann zumindest mit der R4.5 kein geschiess mehr haben was die addon verzeichnisnamen angeht :)

**Comment by ghost** [comment]
> Ich werde das in Zukunft wohl so machen, das ich hier in GIthub die Hierarchie verändere und "redaxo_multiupload -> rex_multiupload" ablege.

momentan ist es halt ein mischmasch. entweder sollte die repo "rex_multiupload" lauten oder halt "redaxo_rex_multiupload".

übrigens habe ich mich gerfagt ob diese zeile hier nicht noch probleme machen wird: https://github.com/nightstomp/redaxo_multiupload/blob/master/config.inc.php#L32

(ich habe bei mir in der master.inc.php diese beta geschichten deshalb auch rausgenommen, bei mir steht nur 4.5.0)

**Comment by gharlan** [comment]
Da er mit [`version_compare()`](http://php.net/manual/de/function.version-compare.php) arbeitet, sollte das kein Problem sein. Die Funktion kommt auch mit Beta-Versionen etc. zurecht.

**Comment by ghost** [comment]
ok, wusst ich net...dachte ein nicht numerisches zeichen könnte da probleme machen.

**Comment by hirbod** [comment]
Added some Magic:
https://github.com/nightstomp/redaxo_multiupload/blob/master/install.inc.php

Ab sofort ist es egal, wie der Ordner heißt. Die Install-Routine kümmert sich darum :)
