### ISSUE TITLE
rex_mediapool_addMediacatOptionsWPerm() ist deprecated

### ISSUE THREAD

**Issue by ghost** [nightstomp/rex_multiupload#8]
Wenn ich bei einem 4.5er Redaxo Dateien in eine Kategorie hochladen möchte, erhalte ich die Fehlermeldung:

 Fatal error: Call to undefined function rex_mediapool_addMediacatOptionsWPerm() in ...\redaxo\include\addons\rex_multiupload\classes\upload.class.php on line 215

Die Klasse ist anscheinend schon länger nicht mehr an Bord und wird über class.compat.inc.php wg. Rückwärtskompatibilität zur Verfügung gestellt. Allerdings muss die class.compat.inc.php in 4.5 von Hand in der /redaxo/include/functions.inc.php (64) einkommentiert werden.

**Comment by hirbod** [comment]
Hi Ingo,

danke für die Meldung. Deine Aussage stimmt aber nicht. Die class.compat.inc.php ist drin. Du hast wahrscheinlich den Branch von Github oder ne Beta geladen, denn das einkommentieren der Class macht das Rex-Paket Building Script.

Ich hab mir eben mal die Rex 4.5 von Redaxo.org geladen und in die functions.inc.php geschaut, in der letzten Zeile siehst du, das die Class drin ist! Hatte aber auch mal das gleiche Problem, lag daran, das ich das GIT-Paket geladen hatte.. Sollte man nie tun..

**Comment by ghost** [comment]
Hi Hirbod

Ich arbeite mit dem gn2-Fork. Ich frag mal Jan dazu. 

LG Ingo

**Comment by jdlx** [comment]
Ich glaub im alten fork war das direkt im file geändert.. kann sein das der edit durch den switch von 4.1.x auf 4.5 wieder rausflog., muß ich mal kucken.

**Comment by jdlx** [comment]
Yup, das wars.. is fixed https://github.com/gn2netwerk/redaxo4/commit/05299736f7a0247c489e6f8848da74a18704ad7f

**Comment by dergel** [comment]
irgendwann werden wir die class.compat.inc.php rauswerfen.. wenn du zeit hast, wäre es super, wenn du den multiuploader unabhaengig davon machst..
